<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-HB25A9N" failures="38" tests="49" name="Trigonometric Function Unit Test" time="0.039" errors="0" timestamp="2024-02-29T13:20:19 MSK">
  <testcase classname="org.rntgroup.CalcUnitTests.CosTest" name="unitCosOfInfinityTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Expected IllegalArgumentException to be thrown, but nothing was thrown">
      <![CDATA[java.lang.AssertionError: Expected IllegalArgumentException to be thrown, but nothing was thrown
at org.rntgroup.CalcUnitTests.CosTest.unitCosOfInfinityTest(CosTest.java:36)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCosOfInfinityTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.SinTest" name="unitSinOfInfinityTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Expected IllegalArgumentException to be thrown, but nothing was thrown">
      <![CDATA[java.lang.AssertionError: Expected IllegalArgumentException to be thrown, but nothing was thrown
at org.rntgroup.CalcUnitTests.SinTest.unitSinOfInfinityTest(SinTest.java:36)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitSinOfInfinityTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.SinTest" name="unitSinTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTests.CosTest" name="unitCosTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [1.0] but found [0.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [1.0] but found [0.0]
at org.rntgroup.CalcUnitTests.CosTest.unitCosTest(CosTest.java:31)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCosTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.SinTest" name="unitSinTest" time="0.001"/>
  <testcase classname="org.rntgroup.CalcUnitTests.CosTest" name="unitCosTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.8660254037844387] but found [0.49999999999999994]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.8660254037844387] but found [0.49999999999999994]
at org.rntgroup.CalcUnitTests.CosTest.unitCosTest(CosTest.java:31)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCosTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.SinTest" name="unitSinTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTests.CosTest" name="unitCosTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.7071067811865476] but found [0.7071067811865475]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.7071067811865476] but found [0.7071067811865475]
at org.rntgroup.CalcUnitTests.CosTest.unitCosTest(CosTest.java:31)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCosTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.SinTest" name="unitSinTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTests.CosTest" name="unitCosTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.5000000000000001] but found [0.8660254037844386]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.5000000000000001] but found [0.8660254037844386]
at org.rntgroup.CalcUnitTests.CosTest.unitCosTest(CosTest.java:31)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCosTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.SinTest" name="unitSinTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTests.CosTest" name="unitCosTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.0] but found [1.0]
at org.rntgroup.CalcUnitTests.CosTest.unitCosTest(CosTest.java:31)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCosTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.SinTest" name="unitSinTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.0] but found [1.2246467991473532E-16]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.0] but found [1.2246467991473532E-16]
at org.rntgroup.CalcUnitTests.SinTest.unitSinTest(SinTest.java:31)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitSinTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.CosTest" name="unitCosTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [-1.0] but found [1.2246467991473532E-16]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [-1.0] but found [1.2246467991473532E-16]
at org.rntgroup.CalcUnitTests.CosTest.unitCosTest(CosTest.java:31)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCosTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.SinTest" name="unitSinTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTests.CosTest" name="unitCosTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.0] but found [-1.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.0] but found [-1.0]
at org.rntgroup.CalcUnitTests.CosTest.unitCosTest(CosTest.java:31)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCosTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.SinTest" name="unitSinTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.0] but found [-2.4492935982947064E-16]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.0] but found [-2.4492935982947064E-16]
at org.rntgroup.CalcUnitTests.SinTest.unitSinTest(SinTest.java:31)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitSinTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.SinTest" name="unitSinTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTests.CosTest" name="unitCosTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [1.0] but found [-2.4492935982947064E-16]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [1.0] but found [-2.4492935982947064E-16]
at org.rntgroup.CalcUnitTests.CosTest.unitCosTest(CosTest.java:31)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCosTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.SinTest" name="unitSinTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTests.SinTest" name="unitSinTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTests.CosTest" name="unitCosTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.0] but found [-1.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.0] but found [-1.0]
at org.rntgroup.CalcUnitTests.CosTest.unitCosTest(CosTest.java:31)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCosTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.SinTest" name="unitSinTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTests.CosTest" name="unitCosTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.7660444431189781] but found [-0.6427876096865391]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.7660444431189781] but found [-0.6427876096865391]
at org.rntgroup.CalcUnitTests.CosTest.unitCosTest(CosTest.java:31)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCosTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.CosTest" name="unitCosTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.9998476951563913] but found [0.01745240643728351]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.9998476951563913] but found [0.01745240643728351]
at org.rntgroup.CalcUnitTests.CosTest.unitCosTest(CosTest.java:31)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCosTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.CosTest" name="unitCosTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [-0.9925461516413221] but found [-0.12186934340514731]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [-0.9925461516413221] but found [-0.12186934340514731]
at org.rntgroup.CalcUnitTests.CosTest.unitCosTest(CosTest.java:31)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCosTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.TgTest" name="unitTgNegativeTest" time="0.003">
    <failure type="java.lang.AssertionError" message="Expected ArithmeticException to be thrown, but nothing was thrown">
      <![CDATA[java.lang.AssertionError: Expected ArithmeticException to be thrown, but nothing was thrown
at org.rntgroup.CalcUnitTests.TgTest.unitTgNegativeTest(TgTest.java:43)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitTgNegativeTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.CtgTest" name="unitCtgNegativeTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Expected ArithmeticException to be thrown, but nothing was thrown">
      <![CDATA[java.lang.AssertionError: Expected ArithmeticException to be thrown, but nothing was thrown
at org.rntgroup.CalcUnitTests.CtgTest.unitCtgNegativeTest(CtgTest.java:43)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCtgNegativeTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.CtgTest" name="unitCtgNegativeTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Expected ArithmeticException to be thrown, but nothing was thrown">
      <![CDATA[java.lang.AssertionError: Expected ArithmeticException to be thrown, but nothing was thrown
at org.rntgroup.CalcUnitTests.CtgTest.unitCtgNegativeTest(CtgTest.java:43)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCtgNegativeTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.TgTest" name="unitTgNegativeTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Expected ArithmeticException to be thrown, but nothing was thrown">
      <![CDATA[java.lang.AssertionError: Expected ArithmeticException to be thrown, but nothing was thrown
at org.rntgroup.CalcUnitTests.TgTest.unitTgNegativeTest(TgTest.java:43)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitTgNegativeTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.TgTest" name="unitTgNegativeTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Expected ArithmeticException to be thrown, but nothing was thrown">
      <![CDATA[java.lang.AssertionError: Expected ArithmeticException to be thrown, but nothing was thrown
at org.rntgroup.CalcUnitTests.TgTest.unitTgNegativeTest(TgTest.java:43)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitTgNegativeTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.CtgTest" name="unitCtgNegativeTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Expected ArithmeticException to be thrown, but nothing was thrown">
      <![CDATA[java.lang.AssertionError: Expected ArithmeticException to be thrown, but nothing was thrown
at org.rntgroup.CalcUnitTests.CtgTest.unitCtgNegativeTest(CtgTest.java:43)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCtgNegativeTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.CtgTest" name="unitCtgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [1.7320508075688767] but found [0.4804727781564516]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [1.7320508075688767] but found [0.4804727781564516]
at org.rntgroup.CalcUnitTests.CtgTest.unitCtgTest(CtgTest.java:27)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCtgTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.TgTest" name="unitTgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.0] but found [NaN]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.0] but found [NaN]
at org.rntgroup.CalcUnitTests.TgTest.unitTgTest(TgTest.java:28)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitTgTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.CtgTest" name="unitCtgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [1.0] but found [0.6557942026326724]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [1.0] but found [0.6557942026326724]
at org.rntgroup.CalcUnitTests.CtgTest.unitCtgTest(CtgTest.java:27)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCtgTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.TgTest" name="unitTgTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.5773502691896257] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.5773502691896257] but found [1.0]
at org.rntgroup.CalcUnitTests.TgTest.unitTgTest(TgTest.java:28)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitTgTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.CtgTest" name="unitCtgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.5773502691896257] but found [0.7807144353592677]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.5773502691896257] but found [0.7807144353592677]
at org.rntgroup.CalcUnitTests.CtgTest.unitCtgTest(CtgTest.java:27)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCtgTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.TgTest" name="unitTgTest" time="0.0"/>
  <testcase classname="org.rntgroup.CalcUnitTests.CtgTest" name="unitCtgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.0] but found [0.9171523356672744]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.0] but found [0.9171523356672744]
at org.rntgroup.CalcUnitTests.CtgTest.unitCtgTest(CtgTest.java:27)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCtgTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.TgTest" name="unitTgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [1.7320508075688767] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [1.7320508075688767] but found [1.0]
at org.rntgroup.CalcUnitTests.TgTest.unitTgTest(TgTest.java:28)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitTgTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.CtgTest" name="unitCtgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.0] but found [0.9998386139886326]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.0] but found [0.9998386139886326]
at org.rntgroup.CalcUnitTests.CtgTest.unitCtgTest(CtgTest.java:27)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCtgTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.TgTest" name="unitTgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.0] but found [1.0]
at org.rntgroup.CalcUnitTests.TgTest.unitTgTest(TgTest.java:28)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitTgTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.CtgTest" name="unitCtgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.0] but found [-0.9171523356672744]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.0] but found [-0.9171523356672744]
at org.rntgroup.CalcUnitTests.CtgTest.unitCtgTest(CtgTest.java:27)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCtgTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.TgTest" name="unitTgTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.0] but found [1.0]
at org.rntgroup.CalcUnitTests.TgTest.unitTgTest(TgTest.java:28)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitTgTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.CtgTest" name="unitCtgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [57.28996163075943] but found [0.01745152054354153]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [57.28996163075943] but found [0.01745152054354153]
at org.rntgroup.CalcUnitTests.CtgTest.unitCtgTest(CtgTest.java:27)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCtgTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.TgTest" name="unitTgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.0] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.0] but found [1.0]
at org.rntgroup.CalcUnitTests.TgTest.unitTgTest(TgTest.java:28)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitTgTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.CtgTest" name="unitCtgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [8.144346427974606] but found [0.9970790482245655]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [8.144346427974606] but found [0.9970790482245655]
at org.rntgroup.CalcUnitTests.CtgTest.unitCtgTest(CtgTest.java:27)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitCtgTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.TgTest" name="unitTgTest" time="0.001">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.017455064928217585] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.017455064928217585] but found [1.0]
at org.rntgroup.CalcUnitTests.TgTest.unitTgTest(TgTest.java:28)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitTgTest -->
  <testcase classname="org.rntgroup.CalcUnitTests.TgTest" name="unitTgTest" time="0.0">
    <failure type="java.lang.AssertionError" message="Result is not correct! expected [0.1227845609029044] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Result is not correct! expected [0.1227845609029044] but found [1.0]
at org.rntgroup.CalcUnitTests.TgTest.unitTgTest(TgTest.java:28)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- unitTgTest -->
</testsuite> <!-- Trigonometric Function Unit Test -->
